### ISSUE TITLE
Bug: Dependabot Breaks CI at PNPM Step

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-site#141]
### What happened?

[Dependabot doesn't support PNPM](https://github.com/dependabot/dependabot-core/issues/1736), which causes our CI to fail with every Dependabot PR. So we've got two choices:
1. Manually update dependencies and close Dependabot PRs (lmao);
2. Swap out to [Renovatebot](https://docs.renovatebot.com/javascript/)

Methinks we could try Renovate out.

### What did you expect to happen?

Our CI should, well, work lmao

### Step(s) to Reproduce

Sit around and wait for a new Dependabot PR.

### Were you on mobile when this happened?

No

### What browsers are you seeing the problem on?

Other

### Other Browser

N/A

**Comment by zysim** [comment]
Re: https://github.com/leaderboardsgg/leaderboard-site/pull/140

**Comment by buffet-time** [comment]
[This PR](https://github.com/leaderboardsgg/leaderboard-site/pull/165) will resolve this.

**Comment by zysim** [comment]
Thank youuuuu
