### ISSUE TITLE
Task: Adding a proper icon library

### ISSUE THREAD

**Issue by maxcaplan** [leaderboardsgg/leaderboard-site#16]
### What are you wanting to be added?

Add a library to handle any icons to be used on the site. 
Requires a discussion to figure out what library works for the majority of contributors.

### What might break?

Any inline `svg`'s that are currently being used in the absence of a library will have to be replaced.

**Comment by CapitaineToinon** [comment]
Since we're using Tailwind, I quite like https://heroicons.com/ made by the same guys. I've also used Fontawesome quite a lot in the past but I think we should avoid projects with such a business model for this repo.

**Comment by squiddot** [comment]
I feel like this is handled with #144
