### ISSUE TITLE
Task: RenderOptions Is Not Generic Anymore

### ISSUE THREAD

**Issue by zysim** [leaderboardsgg/leaderboard-site#215]
### What happened?

In `testUtils.tsL49`, we have `RenderOptions<Vue>`. Problem is that `RenderOptions` isn't generic anymore, which breaks all component rendering tests, and in turn, prevents commits. However, simply removing `<Vue>` isn't possible, since doing _that_ causes the return of the enclosing function, `stubbedRender` to break as well. This is because the new `RenderOptions` does not have a `mocks` and `stubs` property.

### What did you expect to happen?

Tests should succeed.

### Step(s) to Reproduce

Commit some changes.

### Were you on mobile when this happened?

No

### What browsers are you seeing the problem on?

Other

### Other Browser

N/A

### Relevant log output

```javascript
(There's a bunch of repeated errors for all of our components. Pasting just one of them.)

 FAIL  components/blocks/cards/SignUpCard/SignUpCard.test.ts
  ● Test suite failed to run

    testUtils.ts:49:13 - error TS2315: Type 'RenderOptions' is not generic.

    49   options?: RenderOptions<Vue>,
                   ~~~~~~~~~~~~~~~~~~
```

**Comment by erunks** [comment]
Seems related to this: https://github.com/leaderboardsgg/leaderboard-site/pull/177#issuecomment-1046097333
