### ISSUE TITLE
Task: Fix Tailwind component style priorities.

### ISSUE THREAD

**Issue by maxcaplan** [leaderboardsgg/leaderboard-site#29]
### What are you wanting to be added?

We need to have any Tailwind components using `@apply` to also be using `@layer` so that they are in the component layer and their styles can be easily overwritten when the component is used elsewhere in the code base.

Example:
Original Class
```css
.input {
  @apply border border-gray-300 rounded px-3 py-2 focus:outline-none;
}
```
New Class
```css
@layer components {
  .input {
    @apply border border-gray-300 rounded px-3 py-2 focus:outline-none;
  }
}
```
The current fix for this is using `important: true` in `tailwind.config.js`. This is very bad and we want this removed.
[Here](https://tailwindcss.com/docs/functions-and-directives#layer) is a link to Tailwinds docs for `@layer`

### What might break?

Currently using `@layer` causes most of the styles for the component to break. This may be an issue with how Tailwind is set up in the project and will need to be addressed.

**Comment by erunks** [comment]
For more context, we used to use the `@layer` directive, but they were removed because they were breaking things.

References:
- [`Discord mention`](https://discord.com/channels/856595632030613524/856705268829257728/869935519365226527)
- https://github.com/speedrun-website/speedrun.website/pull/18/commits/8a36f51cf7a0ba1dfd98cf5d18822b9e9cb101d9

**Comment by erunks** [comment]
@squiddot do you think this is something that still needs to happen after your big refactor PR #130 ?

**Comment by erunks** [comment]
@maxcaplan @squiddot do we still need this?

**Comment by erunks** [comment]
Closing this, as we apparently don't need it anymore
