### ISSUE TITLE
Feature Request: [Nuxt3] Add I18n

### ISSUE THREAD

**Issue by erunks** [leaderboardsgg/leaderboard-site#388]
### What are you wanting to be added?

We were using [this module](https://i18n.nuxtjs.org/) in `Nuxt2`, and now that we're on `Nuxt3` we need to re-implement this too.

Here's their current checklist before it's ready:
https://github.com/nuxt-community/i18n-module/blob/next/TODO.md

Might need another alternative.

### What might break?

Possibly everything

**Comment by buffet-time** [comment]
Closed by https://github.com/leaderboardsgg/leaderboard-site/pull/506
