### ISSUE TITLE
Feature Request: Create Leaderboard Info Component

### ISSUE THREAD

**Issue by erunks** [leaderboardsgg/leaderboard-site#546]
### What are you wanting to be added?

# Goal: Create the `Leaderboard Info` component
## Objectives:
- [ ] After navigating to `/board/{slug}`, you should see the a profile header for the given user
- [ ] This component should be reactive and mobile first

#### [Figma Component](https://www.figma.com/file/DNCMCfWjft4poxGIgJSHyA/Old-Wireframes?node-id=2012%3A1105&t=ENUZcdeVXAtFinA6-0)

| Mobile design | Desktop design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/17736056/224210896-957a272d-cc5e-4843-8887-d6b77ca1767c.png) | ![image](https://user-images.githubusercontent.com/17736056/224211156-de55b061-c9bf-4131-8727-ef6f880c0c64.png) |

## Things to know:
- If https://github.com/leaderboardsgg/leaderboard-site/issues/545, is not done yet, it's completely fine to have generic defaults in place of actual leaderboard details
- If you don't have access to the [Figma](https://www.figma.com/file/DNCMCfWjft4poxGIgJSHyA/Old-Wireframes?node-id=2012%3A1105&t=ENUZcdeVXAtFinA6-0), that can be found also in the [`#resources`](https://discord.com/channels/856595632030613524/977612207821058168), ask about access to it in [`#general-dev`](https://discord.com/channels/856595632030613524/857014218775986226) and someone should be able to help you out

### What might break?

N/A

### Relevant Issues

#545  is kind of a blocker in terms of getting actual information about the leaderboard. Theoretically, the route should be setup the same, so these two issue should be able to be worked on simultaneously.

**Comment by zysim** [comment]
1. What do we want in the More dropdown?
2. We'll need to source a globe and chat icon somewhere. Where could we get them?
3. Where would the chat button navigate to?

**Comment by erunks** [comment]
1. As far as any of the links go on the leaderboard pages, I think general placeholders are fine for now. We haven't _really_ scoped any of this out yet, and these were just the old figma designs that we had to go off. I imagine that in the end, this will mostly end up being dictated by what the admins want from us in terms of a leaderboard site

2. IIRC we were using [fontawesome](https://fontawesome.com) for a lot of our icons, just downloading the free SVGs and saving them in our file structure.

3. Same thing as 1, I think just a placeholder is fine for now.

**Comment by zysim** [comment]
Found the existing icon folders, since. Seems like you guys have FA Pro plan? I'd need help to get the SVGs for the missing icons

**Comment by erunks** [comment]
Nah, we've just been using the free tier icons, or at least I have. If for some reason these icons are behind the pro plan, I think we should be good to just swap them with the free tier equivalent

**Comment by zysim** [comment]
Ye I'll try to use the free tier whenever possible. Worst case I'll try creating em from scratch lol
