### ISSUE TITLE
Feature Request: Tell user to confirm email.

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-site#591]
### What are you wanting to be added?

Upon successfully signing up for an account, the user should be prompted to confirm their account via a banner or other text on the website. You could even make this banner persist until they confirm their account.

### What might break?

Nothing probably, unless there are already banners.

**Comment by zysim** [comment]
https://github.com/leaderboardsgg/leaderboard-site/issues/592 would solve this, actually.
