### ISSUE TITLE
Feature Request: Resend confirmation email link

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-site#592]
### What are you wanting to be added?

Currently, there is no way to actually resend the confirmation email besides literally just hitting the endpoint manually. There should be a link on the website to resend the confirmation email that appears while logged in but not confirmed.

### What might break?

nothing probably™️

### Relevant Issues

Could be done as part of #591 a la "Don't forget to confirm your account. Click here to resend the confirmation email."

**Comment by zysim** [comment]
We'll need to design the UI for this. I'll work on the logic + a temp UI for it, in the meantime.
