### ISSUE TITLE
Feature Request: Don't print "success!" if success is not guaranteed

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-site#594]
### What are you wanting to be added?

Make it so that when you complete an operation for which the backend doesn't specify whether it succeeded or not, the "Success!" dialog box does not show. Show something else that doesn't mislead the user into thinking the operation succeeded when it might not have. Currently this applies to account signup, sending the account recovery email, and possibly other things.

### What might break?

Nothing's going to break. It's fine. Don't worry about it 🙂

**Comment by zysim** [comment]
Actually we don't mask bad responses on registration. In fact the only action we mask is sending the account recovery emails, now.
