### ISSUE TITLE
Use Nuxt Test Utils/Environment

### ISSUE THREAD

**Issue by TheTedder** [leaderboardsgg/leaderboard-site#618]
### What are you wanting to be added?

Use nuxt test utils for testing composables and such instead of using vue test utils for everything. https://nuxt.com/docs/getting-started/testing

### What might break?

The tests are going to need to be tweaked a bit to work properly.

**Comment by zysim** [comment]
You're working on this with https://github.com/leaderboardsgg/leaderboard-site/issues/592, right?
