### ISSUE TITLE
Can I migrate the project from NPM to PNPM

### ISSUE THREAD

**Issue by buffet-time** [leaderboardsgg/leaderboard-site#98]
### What are you wanting to be added?

Move the project from being just NPM to using [PNPM ](https://pnpm.io/) (like Yarn a faster manager ontop of NPM). 

Yarn 1.x is great but Yarn 2.x+ has too many gotchas and things that make it harder to use over just standard NPM. PNPM remains being basically to the point of just being able to replace npm with pnpm without any hassle for people who've never used it, but getting the faster installs, smaller node modules files, better output, and various other benefits.

### What might break?

A select few packages are a bit poorly implemented and can run into minor issues because of PNPMs hard linking to a cache. However if this is arises a simple one line to a `.npmrc` reverts it to a method which will not cause any conflict but still give many benefits.

**Comment by erunks** [comment]
Apparently github actions don't directly support `PNPM`, gonna try and use this https://github.com/pnpm/action-setup, to see if this helps us switch.

**Comment by CapitaineToinon** [comment]
The step in the workflow to read the node version from nvmrc was removed by accident.
