### ISSUE TITLE
Feature Request: Upgrade Nuxt/ Vue to 3.x

### ISSUE THREAD

**Issue by buffet-time** [leaderboardsgg/leaderboard-site#99]
### What are you wanting to be added?

Upgrading Nuxt/ Vue to latest 3.x versions. This is to gain the drastic performance benefits (lower ram footprint, faster load times, smaller install, and general higher Operations per second), the newer functionality, and etc.

### What might break?

Well obviously quite a lot but I've migrated numerous Vue 2.x apps both personally and professionally to Vue 3.x

### Relevant Issues

#90

**Comment by zysim** [comment]
For posterity; as mentioned in https://github.com/leaderboardsgg/leaderboard-site/pull/177#issuecomment-1046097333, we'd need this issue to be done in order to upgrade [`@testing-library/vue`](https://github.com/testing-library/vue-testing-library/blob/v6.0.0/package.json#L79) to v6.

**Comment by erunks** [comment]
Actively working on a Nuxt3 re-write on this branch:
https://github.com/leaderboardsgg/leaderboard-site/tree/LBGG-nuxt-3

**Comment by buffet-time** [comment]
Nuxt 3 is now main as of today
